services:
    app:
        build: ./
        image: amitnd/worldofgames-app:latest
        command: python3 ./MainGame.py
        stdin_open: true
        tty: true
#        volumes:
#          - ./:/worldofgames/Score

    score:
        build: ./
        image: amitnd/worldofgames-score:latest
        command: python3 ./MainScores.py
        ports:
            - '8777:5000'